#!/bin/bash
#
#SBATCH -o /home/014118_emtic_oncology/Pancreas/interactivity/slurm/logs/%j.%x.%N.out
#SBATCH -e /home/014118_emtic_oncology/Pancreas/interactivity/slurm/logs/%j.%x.%N.err
#SBATCH --mail-type=fail,end
#SBATCH --mail-user=sanne.okel@philips.com

python /home/014118_emtic_oncology/Pancreas/interactivity/repos/ritm_interactive_segmentation/scripts/evaluate_model.py NoBRS --checkpoint=./experiments/iter_mask/pancreatic_duct_hrnet64_iter/000_hrnet64_pancreatic_duct/checkpoints/epoch-79-val-loss-0.33.pth --datasets=Panc --structure=pancreatic_duct --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/pancreatic_duct_hrnet64_iter/000_hrnet64_pancreatic_duct/evaluation_logs --iou-analysis --vis-preds
python /home/014118_emtic_oncology/Pancreas/interactivity/repos/ritm_interactive_segmentation/scripts/evaluate_model.py NoBRS --checkpoint=./experiments/iter_mask/pancreatic_duct_hrnet64_iter/000_hrnet64_pancreatic_duct/checkpoints/epoch-149-val-loss-0.34.pth --datasets=Panc --structure=pancreatic_duct --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/pancreatic_duct_hrnet64_iter/000_hrnet64_pancreatic_duct/evaluation_logs --iou-analysis --vis-preds
python /home/014118_emtic_oncology/Pancreas/interactivity/repos/ritm_interactive_segmentation/scripts/evaluate_model.py NoBRS --checkpoint=./experiments/iter_mask/pancreatic_duct_hrnet64_iter/000_hrnet64_pancreatic_duct/checkpoints/epoch-219-val-loss-0.35.pth --datasets=Panc --structure=pancreatic_duct --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/pancreatic_duct_hrnet64_iter/000_hrnet64_pancreatic_duct/evaluation_logs --iou-analysis --vis-preds
python /home/014118_emtic_oncology/Pancreas/interactivity/repos/ritm_interactive_segmentation/scripts/evaluate_model.py NoBRS --checkpoint=./experiments/iter_mask/tumour_hrnet64_iter/000_hrnet64_tumour/checkpoints/epoch-79-val-loss-0.37.pth --datasets=Panc --structure=tumour --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/tumour_hrnet64_iter/000_hrnet64_tumour/evaluation_logs --iou-analysis --vis-preds
python /home/014118_emtic_oncology/Pancreas/interactivity/repos/ritm_interactive_segmentation/scripts/evaluate_model.py NoBRS --checkpoint=./experiments/iter_mask/tumour_hrnet64_iter/000_hrnet64_tumour/checkpoints/epoch-149-val-loss-0.41.pth --datasets=Panc --structure=tumour --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/tumour_hrnet64_iter/000_hrnet64_tumour/evaluation_logs --iou-analysis --vis-preds
python /home/014118_emtic_oncology/Pancreas/interactivity/repos/ritm_interactive_segmentation/scripts/evaluate_model.py NoBRS --checkpoint=./experiments/iter_mask/tumour_hrnet64_iter/000_hrnet64_tumour/checkpoints/epoch-219-val-loss-0.55.pth --datasets=Panc --structure=tumour --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/tumour_hrnet64_iter/000_hrnet64_tumour/evaluation_logs --iou-analysis --vis-preds
