#!/bin/bash
#
#SBATCH -o /home/014118_emtic_oncology/Pancreas/interactivity/slurm/logs/%j.%x.%N.out
#SBATCH -e /home/014118_emtic_oncology/Pancreas/interactivity/slurm/logs/%j.%x.%N.err
#SBATCH --mail-type=fail,end
#SBATCH --mail-user=sanne.okel@philips.com

python ./scripts/evaluate_model.py NoBRS --exp-path=iter_mask/aorta_hrnet64_iter/013_hrnet64_aorta_radius_1/checkpoints --datasets=Panc_val --structure=aorta --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/aorta_hrnet64_iter/013_hrnet64_aorta_radius_1/evaluation_logs/ --iou-analysis --vis-preds
python ./scripts/evaluate_model.py NoBRS --exp-path=iter_mask/arteria_mesenterica_superior_hrnet64_iter/002_hrnet64_arteria_mesenterica_superior_radius_1/checkpoints --datasets=Panc_val --structure=arteria_mesenterica_superior --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/arteria_mesenterica_superior_hrnet64_iter/002_hrnet64_arteria_mesenterica_superior_radius_1/evaluation_logs/ --iou-analysis --vis-preds
python ./scripts/evaluate_model.py NoBRS --exp-path=iter_mask/common_bile_duct_hrnet64_iter/004_hrnet64_common_bile_duct_radius_1/checkpoints --datasets=Panc_val --structure=common_bile_duct --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/common_bile_duct_hrnet64_iter/004_hrnet64_common_bile_duct_radius_1/evaluation_logs/ --iou-analysis --vis-preds
python ./scripts/evaluate_model.py NoBRS --exp-path=iter_mask/gastroduodenalis_hrnet64_iter/002_hrnet64_gastroduodenalis_radius_1/checkpoints --datasets=Panc_val --structure=gastroduodenalis --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/gastroduodenalis_hrnet64_iter/002_hrnet64_gastroduodenalis_radius_1/evaluation_logs/ --iou-analysis --vis-preds
python ./scripts/evaluate_model.py NoBRS --exp-path=iter_mask/pancreas_hrnet64_iter/003_hrnet64_pancreas_radius_1/checkpoints --datasets=Panc_val --structure=pancreas --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/pancreas_hrnet64_iter/003_hrnet64_pancreas_radius_1/evaluation_logs/ --iou-analysis --vis-preds
python ./scripts/evaluate_model.py NoBRS --exp-path=iter_mask/pancreatic_duct_hrnet64_iter/001_hrnet64_pancreatic_duct_radius_1/checkpoints --datasets=Panc_val --structure=pancreatic_duct --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/pancreatic_duct_hrnet64_iter/001_hrnet64_pancreatic_duct_radius_1/evaluation_logs/ --iou-analysis --vis-preds
python ./scripts/evaluate_model.py NoBRS --exp-path=iter_mask/tumour_hrnet64_iter/002_hrnet64_tumour_radius_1/checkpoints --datasets=Panc_val --structure=tumour --n-clicks=50 --save-ious --print-ious --model-name=hrnet-64-iter-m --logs-path=./experiments/iter_mask/tumour_hrnet64_iter/002_hrnet64_tumour_radius_1/evaluation_logs/ --iou-analysis --vis-preds
